category:   crypto
points:     50
short:      entities
name:       "Entities"
author:     nsychev
description: >
 А что скажете на такую кодировку?
attachments:
  - encrypted.txt
url: https://yadi.sk/i/5u_RtduZ3Ucsz5
flags:
  -
    text:   "ugractf_i_found_charcodes"
