category:   recon
points:     125
short:      address
name:       "Where is hacker?"
author:     nsychev
description: >
  Зачем нам закрывать сайт хакеров, если мы можем просто их арестовать?
  Только мы не знаем, где живет Петр. Награда за название улицы, где он 
  живет - флаг!
url: https://fes.ugractf.ru/
flags:
  -
    text:   "ugra_look_at_all_photos"
