----
category:   stegano
points:     200
short:      raw
name:       "Raw"
author:     nsychev
description: >
  Нам в руки попал файл с важнейшей информацией. Эксперты выяснили, что в данном
  формате нет ничего лишнего — только данные. Но больше ничего сделать не могут.
  Может быть, вы лучше разбираетесь в этом?
attachments:
  - data
hints:
  -
    cost:   50
    text:   Спрятана не текстовая информация
  -
    cost:   100
    text:   Зашифрован звуковой файл
flags:
  -
    text:   "ugractfmorsecodeissimpletodecode"
