category:   crypto
points:     150
short:      cryptoloader
name:       "Crypto loader"
author:     nsychev
description: >
  Мы придумали самый надежный алгоритм шифрования. Он использует
  в случае недостатка сложных величин интернет-соединение и, как 
  видно из исходного кода, использует только хорошие методы 
  шифрования и кодирования. Никто никогда его не расшифрует. Ну а 
  если даже получится, то мы готовы дать $100 (нет) и флаг!
url: https://gist.github.com/nsychev/462653c07391bd50dfe948ddfc42806b
flags:
  -
    text:   "ugractf_xor_is_very_bad_cryptoalgo"
