category:   web
points:     100
short:      sessions
name:       "Broken login"
author:     nsychev
description: >
    Кажется, разработчики этого сайта совсем не думали о безопасности сайта.
    А вам так не кажется?
url: https://login.ugractf.ru
flags:
    - 
        text: "ugractf_use_secure_sessions"